config/routes.rb
Restos::Application.routes.draw do
  resources :customer_receipts

  resources :menus

  resources :tickets

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :cost, :item

  has_many :tickets #for item drop down
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit "Submit New Menu Item"%>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Edit Menu Items</h1>
<h3>Note: </h3>
<h3>ONLY restaurant managers can edit menu items.</h3>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Menu</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.item %></td>
    <td><%= menu.cost %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu Item', new_menu_path %>
<br />
<br />
<br />
<%= button_to 'Tickets Page', tickets_path, :class => "button", :method => :get %>
<%= button_to 'Receipts Page', customer_receipts_path, :class => "button", :method => :get %>

app/views/menus/new.html.erb
<h1>New Menu Item</h1>
<h3>Note: </h3>
<h3>ONLY restaurant managers can create menu items.</h3>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @menu.item %>
</p>

<p>
  <b>Cost:</b>
  <%= @menu.cost %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>