config/routes.rb
Restos::Application.routes.draw do
  resources :customer_receipts

  resources :menus

  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :item_status, :menu_id, :paid_status, :table_number

  belongs_to :menu #for item drop down
  has_many :customer_receipts #for ticket number

  validates_existence_of :menu
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_number, "Waitstaff: Select table number" %><br />
    <%= f.select :table_number, [[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']] %>
  </div>
  <div class="field">
    <%= f.label :menu_id, "Waitstaff: Select item" %><br />
    <%= f.select :menu_id, Menu.find(:all).collect {|m| [(m.item), m.id]} %>
  </div>
  <div class="field">
    <%= f.label :item_status, "Waitstaff: Select New" %><br />
    <%= f.radio_button :item_status, 'New' %> <%= f.label "ticket_new", "New" %> <br />
    <%= f.radio_button :item_status, 'In Progress' %> <%= f.label "ticket_in_progress", "In Progress (COOK ONLY!)" %> <br />
    <%= f.radio_button :item_status, 'Complete' %> <%= f.label "ticket_complete", "Complete (COOK ONLY!)" %> <br />
  </div>
  <div class="field">
    <%= f.label :paid_status, "Waitstaff: Select Not Paid" %><br />
    <%= f.radio_button :paid_status, 'Not Paid' %> <%= f.label "not_paid", "Not Paid" %> <br />
    <%= f.radio_button :paid_status, 'Paid' %> <%= f.label "paid", "Paid (CASHIER ONLY!)" %> <br />
  </div>
  <div class="actions">
    <%= f.submit "Submit New Ticket" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>
<h3>Note: </h3>
<h3>Cooks should ONLY change item status, not items themselves.</h3>
<h3>Cashiers should ONLY edit paid status.</h3>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table>
  <tr>
    <th>Table number</th>
    <th>Item</th>
    <th>Item status</th>
    <th>Paid status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.table_number %></td>
    <td><%= ticket.menu.item %></td>
    <td><%= ticket.item_status %></td>
    <td><%= ticket.paid_status %></td>
    <td><%= link_to 'Show Ticket', ticket %></td>
    <td><%= link_to 'Edit Ticket', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Delete Ticket', ticket, method: :delete, data: { confirm: 'Cooks CANNOT delete tickets! If you are a cook, please hit "Cancel"' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>
<br />
<br />
<br />
<%= button_to 'Menu Page (Restaurant Managers ONLY)', menus_path, :class => "button", :method => :get %>
<%= button_to 'Receipts Page', customer_receipts_path, :class => "button", :method => :get %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>
<h3>Note: </h3>
<h3>ONLY waitstaff can create new tickets. All new tickets should have the status of "New".</h3>
<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Table number:</b>
  <%= @ticket.table_number %>
</p>

<p>
  <b>Menu:</b>
  <%= @ticket.menu.item %>
</p>

<p>
  <b>Item status:</b>
  <%= @ticket.item_status %>
</p>

<p>
  <b>Paid status:</b>
  <%= @ticket.paid_status %>
</p>


<%= link_to 'Edit Ticket', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>