config/routes.rb
Restos::Application.routes.draw do
  resources :customer_receipts

  resources :menus

  resources :tickets

end

app/models/customer_receipt.rb
class CustomerReceipt < ActiveRecord::Base
  attr_accessible :cost, :tax, :ticket_id, :total

  belongs_to :ticket

  def tax
    (self.read_attribute(:cost) * 0.0825).round(2)
  end

  def total
    self.total = self.cost + self.tax
  end
end

app/controllers/customer_receipts_controller.rb
class CustomerReceiptsController < ApplicationController
  # GET /customer_receipts
  # GET /customer_receipts.json
  def index
    @customer_receipts = CustomerReceipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customer_receipts }
    end
  end

  # GET /customer_receipts/1
  # GET /customer_receipts/1.json
  def show
    @customer_receipt = CustomerReceipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer_receipt }
    end
  end

  # GET /customer_receipts/new
  # GET /customer_receipts/new.json
  def new
    @customer_receipt = CustomerReceipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer_receipt }
    end
  end

  # GET /customer_receipts/1/edit
  def edit
    @customer_receipt = CustomerReceipt.find(params[:id])
  end

  # POST /customer_receipts
  # POST /customer_receipts.json
  def create
    @customer_receipt = CustomerReceipt.new(params[:customer_receipt])

    respond_to do |format|
      if @customer_receipt.save
        format.html { redirect_to @customer_receipt, notice: 'Customer receipt was successfully created.' }
        format.json { render json: @customer_receipt, status: :created, location: @customer_receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @customer_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customer_receipts/1
  # PUT /customer_receipts/1.json
  def update
    @customer_receipt = CustomerReceipt.find(params[:id])

    respond_to do |format|
      if @customer_receipt.update_attributes(params[:customer_receipt])
        format.html { redirect_to @customer_receipt, notice: 'Customer receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_receipts/1
  # DELETE /customer_receipts/1.json
  def destroy
    @customer_receipt = CustomerReceipt.find(params[:id])
    @customer_receipt.destroy

    respond_to do |format|
      format.html { redirect_to customer_receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customer_receipts_helper.rb
module CustomerReceiptsHelper
end

app/views/customer_receipts/_form.html.erb
<%= form_for(@customer_receipt) do |f| %>
  <% if @customer_receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_receipt.errors.count, "error") %> prohibited this customer_receipt from being saved:</h2>

      <ul>
      <% @customer_receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id, "Table Number" %><br />
    <%= f.select :ticket_id, Ticket.find(:all).collect {|t| [(t.table_number), t.id]} %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.hidden_field :tax %><br />
    <%= f.hidden_field :tax %>
  </div>
  <div class="field">
    <%= f.hidden_field :total %><br />
    <%= f.hidden_field :total %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Receipt' %>
  </div>
<% end %>

app/views/customer_receipts/edit.html.erb
<h1>Editing customer_receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_receipt %> |
<%= link_to 'Back', customer_receipts_path %>

app/views/customer_receipts/index.html.erb
<h1>Receipt</h1>

<table>
  <tr>
    <th>Table Number</th>
    <th>Cost</th>
    <th>Tax</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customer_receipts.each do |customer_receipt| %>
  <tr>
    <td><%= customer_receipt.ticket.table_number %></td>
    <td><%= customer_receipt.cost %></td>
    <td><%= customer_receipt.tax %></td>
    <td><%= customer_receipt.total %></td>
    <td><%= link_to 'Show', customer_receipt %></td>
    <td><%= link_to 'Edit', edit_customer_receipt_path(customer_receipt) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create Receipt', new_customer_receipt_path %>
<br />
<br />
<br />
<%= button_to 'Menu Page (Restaurant Managers ONLY)', menus_path, :class => "button", :method => :get %>
<%= button_to 'Tickets Page', tickets_path, :class => "button", :method => :get %>

app/views/customer_receipts/new.html.erb
<h1>Create Receipt</h1>
<h3>Instructions to Cashier:</h3>
<h4>Select a table number from the drop down menu. Enter in cost. Click "Create Receipt".</h4>
<%= render 'form' %>

<%= link_to 'Back', customer_receipts_path %>

app/views/customer_receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Table Number:</b>
  <%= @customer_receipt.ticket.table_number %>
</p>

<p>
  <b>Cost:</b>
  <%= @customer_receipt.cost %>
</p>

<p>
  <b>Tax:</b>
  <%= @customer_receipt.tax %>
</p>

<p>
  <b>Total:</b>
  <%= @customer_receipt.total %>
</p>


<%= link_to 'Edit', edit_customer_receipt_path(@customer_receipt) %> |
<%= link_to 'Back', customer_receipts_path %>