config/routes.rb
Restos::Application.routes.draw do
  resources :customer_receipts

  resources :menus

  resources :tickets

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  attr_accessible :menu_id, :tax, :ticket_id, :total

  belongs_to :ticket #for ticket number
  belongs_to :menu #for cost

  def total
    self.total = self.cost * 0.0825
  end

  def cost
    self.cost = ticket.menu.cost
  end

  before_save do
    total
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id, "Table Number" %><br />
    <%= f.select :ticket_id, Ticket.find(:all).collect {|t| [(t.table_number), t.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Edit Receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<h1>Customer Receipt</h1>

<table>
  <tr>
    <th>Ticket Number</th>
    <th>Cost</th>
    <th>Tax</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.ticket.ticket_id %></td>
    <td><%= receipt.ticket.menu_id %></td>
    <td><%= receipt.tax %></td>
    <td><%= receipt.total %></td>
    <td><%= link_to 'Show', receipt %></td>
  </tr>
<% end %>
</table>
<br />
<br />
<%= link_to 'Create Receipt', new_receipt_path %>
<br />
<br />
<br />
<%= button_to 'Menu Page (Restaurant Managers ONLY)', menus_path, :class => "button", :method => :get %>
<%= button_to 'Tickets Page', tickets_path, :class => "button", :method => :get %>

app/views/receipts/new.html.erb
<h1>Create Receipt</h1>
<h3>Instructions to Cashier:</h3>
<h4>Select a table number from the drop down menu. Click "Create Receipt".</h4>
<h4>If there were multiple customers at the table, repeat this process for each instance of that table.</h4>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Table:</b>
  <%= @receipt.ticket.ticket_id %>
</p>

<p>
  <b>Cost:</b>
  <%= @receipt.ticket.menu.cost %>
</p>

<p>
  <b>Tax:</b>
  <%= @receipt.tax %>
</p>

<p>
  <b>Total:</b>
  <%= @receipt.total %>
</p>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>